// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATWYWC4OgjbWUmYp82VHLc7nod5xNcV88',
    appId: '1:492322829897:web:733b2c08e154467a6cb198',
    messagingSenderId: '492322829897',
    projectId: 'caredrop-7cf5b',
    authDomain: 'caredrop-7cf5b.firebaseapp.com',
    storageBucket: 'caredrop-7cf5b.firebasestorage.app',
    measurementId: 'G-9PJH4JGF4C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqpgFr6GouEjtFmw1HACJYGjV3vqBJj3Y',
    appId: '1:492322829897:android:481531442e4af7e66cb198',
    messagingSenderId: '492322829897',
    projectId: 'caredrop-7cf5b',
    storageBucket: 'caredrop-7cf5b.firebasestorage.app',
  );
}
